[workspace]
members = ["web", "cli"]
resolver = "2"

[workspace.package]
version = "3.2.1"
edition = "2024"
repository = "https://github.com/johnallen3d/cargo-dist-explore"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
