[package]
name = "dist"
version = "0.1.4"
edition = "2024"
repository = "https://github.com/johnallen3d/cargo-dist-explore"

[dependencies]

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
