[package]
name = "web"
version.workspace = true
edition.workspace = true
repository.workspace = true

# Don't publish this crate with cargo-dist
[package.metadata.dist]
dist = false

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]