name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          # Use config file approach instead of inline release-type
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

          # Token for creating PRs and releases
          token: ${{ secrets.GITHUB_TOKEN }}
