[package]
name = "web"
version = "0.3.1"
edition.workspace = true
repository.workspace = true

# Don't publish this crate with cargo-dist
[package.metadata.dist]
dist = false

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]